config/routes.rb
Rails.application.routes.draw do
  resources :sectors
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "sectors#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/sector.rb
class Sector < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sectors_controller.rb
class SectorsController < ApplicationController
  before_action :set_sector, only: %i[ show edit update destroy ]

  # GET /sectors or /sectors.json
  def index
    @sectors = Sector.order(:name)
  end

  # GET /sectors/1 or /sectors/1.json
  def show
  end

  # GET /sectors/new
  def new
    @sector = Sector.new
    @random_sector = SectorMaker::Sector.new
    @data = @random_sector.to_s
    @svg = @random_sector.export_as.body
  end

  # GET /sectors/1/edit
  def edit
  end

  # POST /sectors or /sectors.json
  def create
    @sector = Sector.new(sector_params)

    respond_to do |format|
      if @sector.save
        format.html { redirect_to sector_url(@sector), notice: "Sector was successfully created." }
        format.json { render :show, status: :created, location: @sector }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sectors/1 or /sectors/1.json
  def update
    respond_to do |format|
      if @sector.update(sector_params)
        format.html { redirect_to sector_url(@sector), notice: "Sector was successfully updated." }
        format.json { render :show, status: :ok, location: @sector }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sector.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sectors/1 or /sectors/1.json
  def destroy
    @sector.destroy

    respond_to do |format|
      format.html { redirect_to sectors_url, notice: "Sector was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sector
      @sector = Sector.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sector_params
      params.require(:sector).permit(:name, :data)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Aamidal, Sci-fi Adventures in the Three Sisters"

    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/sectors_helper.rb
module SectorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title))%></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body> 
    <%= render "shared/header" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/sectors/_form.html.erb
<%= form_with(model: sector) do |form| %>
  <% if sector.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sector.errors.count, "error") %> prohibited this sector from being saved:</h2>

      <ul>
        <% sector.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, :value => sector.name || "Random Sector" %>
  </div>

  <div>
    <%= form.label :data, style: "display: block" %>
    <%= form.text_area :data, :value => sector.data || @data %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sectors/_sector.html.erb
<div id="<%= dom_id sector %>">
  <p>
    <strong>Name:</strong>
    <%= sector.name %>
  </p>

  <p>
    <strong>Data:</strong>
    <% sector.data.split("\n").each do |hex| %>
      <p> <%= hex %> </p>
    <% end %>
  </p>
</div>

app/views/sectors/edit.html.erb
<h1>Editing sector</h1>

<%= render "form", sector: @sector %>

<br>

<div>
  <%= link_to "Show this sector", @sector %> |
  <%= link_to "Back to sectors", sectors_path %>
</div>

app/views/sectors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sectors</h1>

<div id="sectors">
  <% @sectors.each do |sector| %>
    <p>
      <strong>Name:</strong>
      <%= sector.name %>
    </p>
    <p>
      <%= link_to "Show this sector", sector %>
    </p>
  <% end %>
</div>

<%= link_to "New sector", new_sector_path %>

app/views/sectors/new.html.erb
<div class="wrapper">
  <div class="data">
    <%= render "form", sector: @sector %>
    <%= link_to "Back to sectors", sectors_path %>
  </div>
  <div class="map">
    <img src="<%= @svg %>" alt="A sector map"/>
  </div>
</div>

app/views/sectors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @sector %>

<div>
  <%= link_to "Edit this sector", edit_sector_path(@sector) %> |
  <%= link_to "Back to sectors", sectors_path %>

  <%= button_to "Destroy this sector", @sector, method: :delete %>
</div>

app/views/shared/_footer.html.erb
<footer>
  The Traveller game in all forms is owned by Far Future Enterprises.
  Copyright © 1977 - 2022 Far Future Enterprises.
</footer>